name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole excel_checker.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: excel_checker.exe
        path: dist/
        
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: excel_checker.exe
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: excel_checker.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
